name: Build MUSL cross

on:
  push:
    branches: 
      - "*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual run'

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         target: [armv7l-linux-musleabihf,aarch64-linux-musl,x86_64-linux-musl]
         #target: [armv7l-linux-musleabihf]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone upstream
        run: git clone --depth=1 https://git.zv.io/toolchains/musl-cross-make.git musl-cross
      - name: Copy our config
        run: cp config.mak.${{ matrix.target }} musl-cross/config.mak
      - name: Build
        run: |
             cd musl-cross
             make -j$(nproc)
      - name: Listing
        run: |
             ls -al
             ls -al musl-cross
      - name: Compress ${{ matrix.target }}-cross
        run: |
             sudo apt update
             sudo apt install -y tar
             tar -czf ${{ matrix.target }}.tar.gz musl-cross/${{ matrix.target }}
             
      - name: Upload ${{ matrix.target }}-cross artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-cross.tar.gz
          path: ${{ matrix.target }}-cross.tar.gz
