name: Build MUSL cross

on:
  push:
    branches: 
      - "*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual run'

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         target: [armv7l-linux-musleabihf,aarch64-linux-musl,x86_64-linux-musl]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone upstream
        run: git clone --depth=1 https://git.zv.io/toolchains/musl-cross-make.git musl-cross
      #- name: Copy our config
      #  run: cp config.mak.${{ matrix.target }} musl-cross/config.mak
      - name: Build
        run: |
             cd musl-cross
             make -j$(nproc) BINUTILS_VER=2.39 GCC_VER=12.2.0 MUSL_VER=1.2.4 OUTPUT=${{ matrix.target }} TARGET=${{ matrix.target }}
             make install
             ls -al ./${{ matrix.target }}
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./musl-cross/${{ matrix.target }}
          files: |
            ./*
          outPath: ${{ matrix.target }}.tar.gz
      - name: Upload ${{ matrix.target }}-cross artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-cross.tar.gz
          path: ${{ matrix.target }}-cross.tar.gz
